# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.element_api import ElementApi


class TestElementApi(unittest.TestCase):
    """ ElementApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.element_api.ElementApi()

    def tearDown(self):
        pass

    def test_element_add_referenced_element(self):
        """
        Test case for element_add_referenced_element

        Add a reference to an existing element to the child elements collection.
        """
        pass

    def test_element_create_analysis(self):
        """
        Test case for element_create_analysis

        Create an Analysis.
        """
        pass

    def test_element_create_attribute(self):
        """
        Test case for element_create_attribute

        Create a new attribute of the specified element.
        """
        pass

    def test_element_create_config(self):
        """
        Test case for element_create_config

        Executes the create configuration function of the data references found within the attributes of the element, and optionally, its children.
        """
        pass

    def test_element_create_element(self):
        """
        Test case for element_create_element

        Create a child element.
        """
        pass

    def test_element_create_search_by_attribute(self):
        """
        Test case for element_create_search_by_attribute

        Create a link for a \"Search Elements By Attribute Value\" operation, whose queries are specified in the request content. The SearchRoot is specified by the Web Id of the root Element. If the SearchRoot is not specified, then the search starts at the Asset Database. ElementTemplate must be provided as the Web ID of the ElementTemplate, which are used to create the Elements. All the attributes in the queries must be defined as AttributeTemplates on the ElementTemplate. An array of attribute value queries are ANDed together to find the desired Element objects. At least one value query must be specified. There are limitations on SearchOperators.
        """
        pass

    def test_element_create_security_entry(self):
        """
        Test case for element_create_security_entry

        Create a security entry owned by the element.
        """
        pass

    def test_element_delete(self):
        """
        Test case for element_delete

        Delete an element.
        """
        pass

    def test_element_delete_security_entry(self):
        """
        Test case for element_delete_security_entry

        Delete a security entry owned by the element.
        """
        pass

    def test_element_execute_search_by_attribute(self):
        """
        Test case for element_execute_search_by_attribute

        Execute a \"Search Elements By Attribute Value\" operation.
        """
        pass

    def test_element_find_element_attributes(self):
        """
        Test case for element_find_element_attributes

        Retrieves a list of element attributes matching the specified filters from the specified element.
        """
        pass

    def test_element_get(self):
        """
        Test case for element_get

        Retrieve an element.
        """
        pass

    def test_element_get_analyses(self):
        """
        Test case for element_get_analyses

        Retrieve analyses based on the specified conditions.
        """
        pass

    def test_element_get_attributes(self):
        """
        Test case for element_get_attributes

        Get the attributes of the specified element.
        """
        pass

    def test_element_get_by_path(self):
        """
        Test case for element_get_by_path

        Retrieve an element by path.
        """
        pass

    def test_element_get_categories(self):
        """
        Test case for element_get_categories

        Get an element's categories.
        """
        pass

    def test_element_get_elements(self):
        """
        Test case for element_get_elements

        Retrieve elements based on the specified conditions. By default, this method selects immediate children of the specified element.
        """
        pass

    def test_element_get_event_frames(self):
        """
        Test case for element_get_event_frames

        Retrieve event frames that reference this element based on the specified conditions. By default, returns all event frames that reference this element with a start time in the past 8 hours.
        """
        pass

    def test_element_get_multiple(self):
        """
        Test case for element_get_multiple

        Retrieve multiple elements by web id or path.
        """
        pass

    def test_element_get_referenced_elements(self):
        """
        Test case for element_get_referenced_elements

        Retrieve referenced elements based on the specified conditions. By default, this method selects all referenced elements of the current resource.
        """
        pass

    def test_element_get_security(self):
        """
        Test case for element_get_security

        Get the security information of the specified security item associated with the element for a specified user.
        """
        pass

    def test_element_get_security_entries(self):
        """
        Test case for element_get_security_entries

        Retrieve the security entries associated with the element based on the specified criteria. By default, all security entries for this element are returned.
        """
        pass

    def test_element_get_security_entry_by_name(self):
        """
        Test case for element_get_security_entry_by_name

        Retrieve the security entry associated with the element with the specified name.
        """
        pass

    def test_element_remove_referenced_element(self):
        """
        Test case for element_remove_referenced_element

        Remove a reference to an existing element from the child elements collection.
        """
        pass

    def test_element_update(self):
        """
        Test case for element_update

        Update an element by replacing items in its definition.
        """
        pass

    def test_element_update_security_entry(self):
        """
        Test case for element_update_security_entry

        Update a security entry owned by the element.
        """
        pass


if __name__ == '__main__':
    unittest.main()
