# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_5_links import InlineResponse2005Links


class TestInlineResponse2005Links(unittest.TestCase):
    """ InlineResponse2005Links unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2005Links(self):
        """
        Test InlineResponse2005Links
        """
        model = swagger_client.models.inline_response_200_5_links.InlineResponse2005Links()


if __name__ == '__main__':
    unittest.main()
