# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.analysis_template_api import AnalysisTemplateApi


class TestAnalysisTemplateApi(unittest.TestCase):
    """ AnalysisTemplateApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.analysis_template_api.AnalysisTemplateApi()

    def tearDown(self):
        pass

    def test_analysis_template_create_from_analysis(self):
        """
        Test case for analysis_template_create_from_analysis

        Create an Analysis template based upon a specified Analysis.
        """
        pass

    def test_analysis_template_create_security_entry(self):
        """
        Test case for analysis_template_create_security_entry

        Create a security entry owned by the analysis template.
        """
        pass

    def test_analysis_template_delete(self):
        """
        Test case for analysis_template_delete

        Delete an analysis template.
        """
        pass

    def test_analysis_template_delete_security_entry(self):
        """
        Test case for analysis_template_delete_security_entry

        Delete a security entry owned by the analysis template.
        """
        pass

    def test_analysis_template_get(self):
        """
        Test case for analysis_template_get

        Retrieve an analysis template.
        """
        pass

    def test_analysis_template_get_by_path(self):
        """
        Test case for analysis_template_get_by_path

        Retrieve an analysis template by path.
        """
        pass

    def test_analysis_template_get_categories(self):
        """
        Test case for analysis_template_get_categories

        Get an analysis template's categories.
        """
        pass

    def test_analysis_template_get_security(self):
        """
        Test case for analysis_template_get_security

        Get the security information of the specified security item associated with the analysis template for a specified user.
        """
        pass

    def test_analysis_template_get_security_entries(self):
        """
        Test case for analysis_template_get_security_entries

        Retrieve the security entries associated with the analysis template based on the specified criteria. By default, all security entries for this analysis template are returned.
        """
        pass

    def test_analysis_template_get_security_entry_by_name(self):
        """
        Test case for analysis_template_get_security_entry_by_name

        Retrieve the security entry associated with the analysis template with the specified name.
        """
        pass

    def test_analysis_template_update(self):
        """
        Test case for analysis_template_update

        Update an analysis template by replacing items in its definition.
        """
        pass

    def test_analysis_template_update_security_entry(self):
        """
        Test case for analysis_template_update_security_entry

        Update a security entry owned by the analysis template.
        """
        pass


if __name__ == '__main__':
    unittest.main()
