# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.unit_api import UnitApi


class TestUnitApi(unittest.TestCase):
    """ UnitApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.unit_api.UnitApi()

    def tearDown(self):
        pass

    def test_unit_delete(self):
        """
        Test case for unit_delete

        Delete a unit.
        """
        pass

    def test_unit_get(self):
        """
        Test case for unit_get

        Retrieve a unit.
        """
        pass

    def test_unit_get_by_path(self):
        """
        Test case for unit_get_by_path

        Retrieve a unit by path.
        """
        pass

    def test_unit_update(self):
        """
        Test case for unit_update

        Update a unit.
        """
        pass


if __name__ == '__main__':
    unittest.main()
