# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.attribute_trait_api import AttributeTraitApi


class TestAttributeTraitApi(unittest.TestCase):
    """ AttributeTraitApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.attribute_trait_api.AttributeTraitApi()

    def tearDown(self):
        pass

    def test_attribute_trait_get(self):
        """
        Test case for attribute_trait_get

        Retrieve an attribute trait.
        """
        pass

    def test_attribute_trait_get_by_category(self):
        """
        Test case for attribute_trait_get_by_category

        Retrieve all attribute traits of the specified category/categories.
        """
        pass


if __name__ == '__main__':
    unittest.main()
