# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_32_items import InlineResponse20032Items


class TestInlineResponse20032Items(unittest.TestCase):
    """ InlineResponse20032Items unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20032Items(self):
        """
        Test InlineResponse20032Items
        """
        model = swagger_client.models.inline_response_200_32_items.InlineResponse20032Items()


if __name__ == '__main__':
    unittest.main()
