# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.security_entry_14 import SecurityEntry14


class TestSecurityEntry14(unittest.TestCase):
    """ SecurityEntry14 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityEntry14(self):
        """
        Test SecurityEntry14
        """
        model = swagger_client.models.security_entry_14.SecurityEntry14()


if __name__ == '__main__':
    unittest.main()
