# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.event_frame_2 import EventFrame2


class TestEventFrame2(unittest.TestCase):
    """ EventFrame2 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventFrame2(self):
        """
        Test EventFrame2
        """
        model = swagger_client.models.event_frame_2.EventFrame2()


if __name__ == '__main__':
    unittest.main()
