# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.stream_api import StreamApi


class TestStreamApi(unittest.TestCase):
    """ StreamApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.stream_api.StreamApi()

    def tearDown(self):
        pass

    def test_stream_get_channel(self):
        """
        Test case for stream_get_channel

        Opens a channel that will send messages about any value changes for the specified stream.
        """
        pass

    def test_stream_get_end(self):
        """
        Test case for stream_get_end

        Returns the end-of-stream value of the stream.
        """
        pass

    def test_stream_get_interpolated(self):
        """
        Test case for stream_get_interpolated

        Retrieves interpolated values over the specified time range at the specified sampling interval.
        """
        pass

    def test_stream_get_interpolated_at_times(self):
        """
        Test case for stream_get_interpolated_at_times

        Retrieves interpolated values over the specified time range at the specified sampling interval.
        """
        pass

    def test_stream_get_plot(self):
        """
        Test case for stream_get_plot

        Retrieves values over the specified time range suitable for plotting over the number of intervals (typically represents pixels).
        """
        pass

    def test_stream_get_recorded(self):
        """
        Test case for stream_get_recorded

        Returns a list of compressed values for the requested time range from the source provider.
        """
        pass

    def test_stream_get_recorded_at_time(self):
        """
        Test case for stream_get_recorded_at_time

        Returns a single recorded value based on the passed time and retrieval mode from the stream.
        """
        pass

    def test_stream_get_recorded_at_times(self):
        """
        Test case for stream_get_recorded_at_times

        Retrieves recorded values at the specified times.
        """
        pass

    def test_stream_get_summary(self):
        """
        Test case for stream_get_summary

        Returns a summary over the specified time range for the stream.
        """
        pass

    def test_stream_get_value(self):
        """
        Test case for stream_get_value

        Returns the value of the stream at the specified time. By default, this is usually the current value.
        """
        pass

    def test_stream_update_value(self):
        """
        Test case for stream_update_value

        Updates a value for the specified stream.
        """
        pass

    def test_stream_update_values(self):
        """
        Test case for stream_update_values

        Updates multiple values for the specified stream.
        """
        pass


if __name__ == '__main__':
    unittest.main()
