# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.stream_set_api import StreamSetApi


class TestStreamSetApi(unittest.TestCase):
    """ StreamSetApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.stream_set_api.StreamSetApi()

    def tearDown(self):
        pass

    def test_stream_set_get_channel(self):
        """
        Test case for stream_set_get_channel

        Opens a channel that will send messages about any value changes for the attributes of an Element, Event Frame, or Attribute.
        """
        pass

    def test_stream_set_get_channel_ad_hoc(self):
        """
        Test case for stream_set_get_channel_ad_hoc

        Opens a channel that will send messages about any value changes for the specified streams.
        """
        pass

    def test_stream_set_get_end(self):
        """
        Test case for stream_set_get_end

        Returns End of stream values of the attributes for an Element, Event Frame or Attribute
        """
        pass

    def test_stream_set_get_end_ad_hoc(self):
        """
        Test case for stream_set_get_end_ad_hoc

        Returns End Of Stream values for attributes of the specified streams
        """
        pass

    def test_stream_set_get_interpolated(self):
        """
        Test case for stream_set_get_interpolated

        Returns interpolated values of attributes for an element, event frame or attribute over the specified time range at the specified sampling interval.
        """
        pass

    def test_stream_set_get_interpolated_ad_hoc(self):
        """
        Test case for stream_set_get_interpolated_ad_hoc

        Returns interpolated values of the specified streams over the specified time range at the specified sampling interval.
        """
        pass

    def test_stream_set_get_interpolated_at_times(self):
        """
        Test case for stream_set_get_interpolated_at_times

        Returns interpolated values of attributes for an element, event frame or attribute at the specified times.
        """
        pass

    def test_stream_set_get_interpolated_at_times_ad_hoc(self):
        """
        Test case for stream_set_get_interpolated_at_times_ad_hoc

        Returns interpolated values of the specified streams at the specified times.
        """
        pass

    def test_stream_set_get_plot(self):
        """
        Test case for stream_set_get_plot

        Returns values of attributes for an element, event frame or attribute over the specified time range suitable for plotting over the number of intervals (typically represents pixels).
        """
        pass

    def test_stream_set_get_plot_ad_hoc(self):
        """
        Test case for stream_set_get_plot_ad_hoc

        Returns values of attributes for the specified streams over the specified time range suitable for plotting over the number of intervals (typically represents pixels).
        """
        pass

    def test_stream_set_get_recorded(self):
        """
        Test case for stream_set_get_recorded

        Returns recorded values of the attributes for an element, event frame, or attribute.
        """
        pass

    def test_stream_set_get_recorded_ad_hoc(self):
        """
        Test case for stream_set_get_recorded_ad_hoc

        Returns recorded values of the specified streams.
        """
        pass

    def test_stream_set_get_recorded_at_time(self):
        """
        Test case for stream_set_get_recorded_at_time

        Returns recorded values of the attributes for an element, event frame, or attribute.
        """
        pass

    def test_stream_set_get_recorded_at_time_ad_hoc(self):
        """
        Test case for stream_set_get_recorded_at_time_ad_hoc

        Returns recorded values based on the passed time and retrieval mode.
        """
        pass

    def test_stream_set_get_recorded_at_times(self):
        """
        Test case for stream_set_get_recorded_at_times

        Returns recorded values of attributes for an element, event frame or attribute at the specified times.
        """
        pass

    def test_stream_set_get_recorded_at_times_ad_hoc(self):
        """
        Test case for stream_set_get_recorded_at_times_ad_hoc

        Returns recorded values of the specified streams at the specified times.
        """
        pass

    def test_stream_set_get_summaries(self):
        """
        Test case for stream_set_get_summaries

        Returns summary values of the attributes for an element, event frame or attribute.
        """
        pass

    def test_stream_set_get_summaries_ad_hoc(self):
        """
        Test case for stream_set_get_summaries_ad_hoc

        Returns summary values of the specified streams.
        """
        pass

    def test_stream_set_get_values(self):
        """
        Test case for stream_set_get_values

        Returns values of the attributes for an Element, Event Frame or Attribute at the specified time.
        """
        pass

    def test_stream_set_get_values_ad_hoc(self):
        """
        Test case for stream_set_get_values_ad_hoc

        Returns values of the specified streams.
        """
        pass

    def test_stream_set_update_value(self):
        """
        Test case for stream_set_update_value

        Updates a single value for the specified streams.
        """
        pass

    def test_stream_set_update_value_ad_hoc(self):
        """
        Test case for stream_set_update_value_ad_hoc

        Updates a single value for the specified streams.
        """
        pass

    def test_stream_set_update_values(self):
        """
        Test case for stream_set_update_values

        Updates multiple values for the specified streams.
        """
        pass

    def test_stream_set_update_values_ad_hoc(self):
        """
        Test case for stream_set_update_values_ad_hoc

        Updates multiple values for the specified streams.
        """
        pass


if __name__ == '__main__':
    unittest.main()
