# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.attribute_template_api import AttributeTemplateApi


class TestAttributeTemplateApi(unittest.TestCase):
    """ AttributeTemplateApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.attribute_template_api.AttributeTemplateApi()

    def tearDown(self):
        pass

    def test_attribute_template_create_attribute_template(self):
        """
        Test case for attribute_template_create_attribute_template

        Create an attribute template as a child of another attribute template.
        """
        pass

    def test_attribute_template_delete(self):
        """
        Test case for attribute_template_delete

        Delete an attribute template.
        """
        pass

    def test_attribute_template_get(self):
        """
        Test case for attribute_template_get

        Retrieve an attribute template.
        """
        pass

    def test_attribute_template_get_attribute_templates(self):
        """
        Test case for attribute_template_get_attribute_templates

        Retrieve an attribute template's child attribute templates.
        """
        pass

    def test_attribute_template_get_by_path(self):
        """
        Test case for attribute_template_get_by_path

        Retrieve an attribute template by path.
        """
        pass

    def test_attribute_template_get_categories(self):
        """
        Test case for attribute_template_get_categories

        Get an attribute template's categories.
        """
        pass

    def test_attribute_template_update(self):
        """
        Test case for attribute_template_update

        Update an existing attribute template by replacing items in its definition.
        """
        pass


if __name__ == '__main__':
    unittest.main()
