# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """ SystemApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.system_api.SystemApi()

    def tearDown(self):
        pass

    def test_system_cache_instances(self):
        """
        Test case for system_cache_instances

        Get AF cache instances currently in use by the system. These are caches from which user requests are serviced. The number of instances depends on the number of users connected to the service, the service's authentication method, and the cache instance configuration.
        """
        pass

    def test_system_landing(self):
        """
        Test case for system_landing

        Get system links for this PI System Web API instance.
        """
        pass

    def test_system_status(self):
        """
        Test case for system_status

        Get the system uptime, the system state and the number of cache instances for this PI System Web API instance.
        """
        pass

    def test_system_user_info(self):
        """
        Test case for system_user_info

        Get information about the Windows identity used to fulfill the request. This depends on the service's authentication method and the credentials passed by the client. The impersonation level of the Windows identity is included.
        """
        pass

    def test_system_versions(self):
        """
        Test case for system_versions

        Get the current versions of the PI Web API instance and all external plugins.
        """
        pass


if __name__ == '__main__':
    unittest.main()
