# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.calculation_api import CalculationApi


class TestCalculationApi(unittest.TestCase):
    """ CalculationApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.calculation_api.CalculationApi()

    def tearDown(self):
        pass

    def test_calculation_get_at_intervals(self):
        """
        Test case for calculation_get_at_intervals

        Returns results of evaluating the expression over the time range from the start time to the end time at a defined interval.
        """
        pass

    def test_calculation_get_at_recorded(self):
        """
        Test case for calculation_get_at_recorded

        Returns the result of evaluating the expression at each point in time over the time range from the start time to the end time where a recorded value exists for a member of the expression.
        """
        pass

    def test_calculation_get_at_times(self):
        """
        Test case for calculation_get_at_times

        Returns the result of evaluating the expression at the specified timestamps.
        """
        pass

    def test_calculation_get_summary(self):
        """
        Test case for calculation_get_summary

        Returns the result of evaluating the expression over the time range from the start time to the end time. The time range is first divided into a number of summary intervals. Then the calculation is performed for the specified summaries over each interval.
        """
        pass


if __name__ == '__main__':
    unittest.main()
