# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_30_links import InlineResponse20030Links


class TestInlineResponse20030Links(unittest.TestCase):
    """ InlineResponse20030Links unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20030Links(self):
        """
        Test InlineResponse20030Links
        """
        model = swagger_client.models.inline_response_200_30_links.InlineResponse20030Links()


if __name__ == '__main__':
    unittest.main()
