# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Element(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, web_id=None, id=None, name=None, description=None, path=None, template_name=None, has_children=None, category_names=None, extended_properties=None, links=None):
        """
        Element - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'web_id': 'str',
            'id': 'str',
            'name': 'str',
            'description': 'str',
            'path': 'str',
            'template_name': 'str',
            'has_children': 'bool',
            'category_names': 'list[str]',
            'extended_properties': 'dict(str, InlineResponse2009ExtendedProperties)',
            'links': 'InlineResponse20015Links'
        }

        self.attribute_map = {
            'web_id': 'WebId',
            'id': 'Id',
            'name': 'Name',
            'description': 'Description',
            'path': 'Path',
            'template_name': 'TemplateName',
            'has_children': 'HasChildren',
            'category_names': 'CategoryNames',
            'extended_properties': 'ExtendedProperties',
            'links': 'Links'
        }

        self._web_id = web_id
        self._id = id
        self._name = name
        self._description = description
        self._path = path
        self._template_name = template_name
        self._has_children = has_children
        self._category_names = category_names
        self._extended_properties = extended_properties
        self._links = links

    @property
    def web_id(self):
        """
        Gets the web_id of this Element.

        :return: The web_id of this Element.
        :rtype: str
        """
        return self._web_id

    @web_id.setter
    def web_id(self, web_id):
        """
        Sets the web_id of this Element.

        :param web_id: The web_id of this Element.
        :type: str
        """

        self._web_id = web_id

    @property
    def id(self):
        """
        Gets the id of this Element.

        :return: The id of this Element.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Element.

        :param id: The id of this Element.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Element.

        :return: The name of this Element.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Element.

        :param name: The name of this Element.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this Element.

        :return: The description of this Element.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Element.

        :param description: The description of this Element.
        :type: str
        """

        self._description = description

    @property
    def path(self):
        """
        Gets the path of this Element.

        :return: The path of this Element.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this Element.

        :param path: The path of this Element.
        :type: str
        """

        self._path = path

    @property
    def template_name(self):
        """
        Gets the template_name of this Element.

        :return: The template_name of this Element.
        :rtype: str
        """
        return self._template_name

    @template_name.setter
    def template_name(self, template_name):
        """
        Sets the template_name of this Element.

        :param template_name: The template_name of this Element.
        :type: str
        """

        self._template_name = template_name

    @property
    def has_children(self):
        """
        Gets the has_children of this Element.

        :return: The has_children of this Element.
        :rtype: bool
        """
        return self._has_children

    @has_children.setter
    def has_children(self, has_children):
        """
        Sets the has_children of this Element.

        :param has_children: The has_children of this Element.
        :type: bool
        """

        self._has_children = has_children

    @property
    def category_names(self):
        """
        Gets the category_names of this Element.

        :return: The category_names of this Element.
        :rtype: list[str]
        """
        return self._category_names

    @category_names.setter
    def category_names(self, category_names):
        """
        Sets the category_names of this Element.

        :param category_names: The category_names of this Element.
        :type: list[str]
        """

        self._category_names = category_names

    @property
    def extended_properties(self):
        """
        Gets the extended_properties of this Element.

        :return: The extended_properties of this Element.
        :rtype: dict(str, InlineResponse2009ExtendedProperties)
        """
        return self._extended_properties

    @extended_properties.setter
    def extended_properties(self, extended_properties):
        """
        Sets the extended_properties of this Element.

        :param extended_properties: The extended_properties of this Element.
        :type: dict(str, InlineResponse2009ExtendedProperties)
        """

        self._extended_properties = extended_properties

    @property
    def links(self):
        """
        Gets the links of this Element.

        :return: The links of this Element.
        :rtype: InlineResponse20015Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this Element.

        :param links: The links of this Element.
        :type: InlineResponse20015Links
        """

        self._links = links

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Element):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
