# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2004Links(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _self=None, securable_object=None, security_identity=None):
        """
        InlineResponse2004Links - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_self': 'str',
            'securable_object': 'str',
            'security_identity': 'str'
        }

        self.attribute_map = {
            '_self': 'Self',
            'securable_object': 'SecurableObject',
            'security_identity': 'SecurityIdentity'
        }

        self.__self = _self
        self._securable_object = securable_object
        self._security_identity = security_identity

    @property
    def _self(self):
        """
        Gets the _self of this InlineResponse2004Links.

        :return: The _self of this InlineResponse2004Links.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """
        Sets the _self of this InlineResponse2004Links.

        :param _self: The _self of this InlineResponse2004Links.
        :type: str
        """

        self.__self = _self

    @property
    def securable_object(self):
        """
        Gets the securable_object of this InlineResponse2004Links.

        :return: The securable_object of this InlineResponse2004Links.
        :rtype: str
        """
        return self._securable_object

    @securable_object.setter
    def securable_object(self, securable_object):
        """
        Sets the securable_object of this InlineResponse2004Links.

        :param securable_object: The securable_object of this InlineResponse2004Links.
        :type: str
        """

        self._securable_object = securable_object

    @property
    def security_identity(self):
        """
        Gets the security_identity of this InlineResponse2004Links.

        :return: The security_identity of this InlineResponse2004Links.
        :rtype: str
        """
        return self._security_identity

    @security_identity.setter
    def security_identity(self, security_identity):
        """
        Sets the security_identity of this InlineResponse2004Links.

        :param security_identity: The security_identity of this InlineResponse2004Links.
        :type: str
        """

        self._security_identity = security_identity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2004Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
