# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20033(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, items=None, units_abbreviation=None):
        """
        InlineResponse20033 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'items': 'list[InlineResponse20028]',
            'units_abbreviation': 'str'
        }

        self.attribute_map = {
            'items': 'Items',
            'units_abbreviation': 'UnitsAbbreviation'
        }

        self._items = items
        self._units_abbreviation = units_abbreviation

    @property
    def items(self):
        """
        Gets the items of this InlineResponse20033.

        :return: The items of this InlineResponse20033.
        :rtype: list[InlineResponse20028]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this InlineResponse20033.

        :param items: The items of this InlineResponse20033.
        :type: list[InlineResponse20028]
        """

        self._items = items

    @property
    def units_abbreviation(self):
        """
        Gets the units_abbreviation of this InlineResponse20033.

        :return: The units_abbreviation of this InlineResponse20033.
        :rtype: str
        """
        return self._units_abbreviation

    @units_abbreviation.setter
    def units_abbreviation(self, units_abbreviation):
        """
        Sets the units_abbreviation of this InlineResponse20033.

        :param units_abbreviation: The units_abbreviation of this InlineResponse20033.
        :type: str
        """

        self._units_abbreviation = units_abbreviation

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20033):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
