# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2006(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, web_id=None, id=None, name=None, description=None, path=None, config_string=None, display_string=None, editor_type=None, has_children=None, is_configured=None, is_initializing=None, plug_in_name=None, supported_behaviors=None, variable_mapping=None, links=None):
        """
        InlineResponse2006 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'web_id': 'str',
            'id': 'str',
            'name': 'str',
            'description': 'str',
            'path': 'str',
            'config_string': 'str',
            'display_string': 'str',
            'editor_type': 'str',
            'has_children': 'bool',
            'is_configured': 'bool',
            'is_initializing': 'bool',
            'plug_in_name': 'str',
            'supported_behaviors': 'list[str]',
            'variable_mapping': 'str',
            'links': 'InlineResponse2006Links'
        }

        self.attribute_map = {
            'web_id': 'WebId',
            'id': 'Id',
            'name': 'Name',
            'description': 'Description',
            'path': 'Path',
            'config_string': 'ConfigString',
            'display_string': 'DisplayString',
            'editor_type': 'EditorType',
            'has_children': 'HasChildren',
            'is_configured': 'IsConfigured',
            'is_initializing': 'IsInitializing',
            'plug_in_name': 'PlugInName',
            'supported_behaviors': 'SupportedBehaviors',
            'variable_mapping': 'VariableMapping',
            'links': 'Links'
        }

        self._web_id = web_id
        self._id = id
        self._name = name
        self._description = description
        self._path = path
        self._config_string = config_string
        self._display_string = display_string
        self._editor_type = editor_type
        self._has_children = has_children
        self._is_configured = is_configured
        self._is_initializing = is_initializing
        self._plug_in_name = plug_in_name
        self._supported_behaviors = supported_behaviors
        self._variable_mapping = variable_mapping
        self._links = links

    @property
    def web_id(self):
        """
        Gets the web_id of this InlineResponse2006.

        :return: The web_id of this InlineResponse2006.
        :rtype: str
        """
        return self._web_id

    @web_id.setter
    def web_id(self, web_id):
        """
        Sets the web_id of this InlineResponse2006.

        :param web_id: The web_id of this InlineResponse2006.
        :type: str
        """

        self._web_id = web_id

    @property
    def id(self):
        """
        Gets the id of this InlineResponse2006.

        :return: The id of this InlineResponse2006.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InlineResponse2006.

        :param id: The id of this InlineResponse2006.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this InlineResponse2006.

        :return: The name of this InlineResponse2006.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this InlineResponse2006.

        :param name: The name of this InlineResponse2006.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this InlineResponse2006.

        :return: The description of this InlineResponse2006.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this InlineResponse2006.

        :param description: The description of this InlineResponse2006.
        :type: str
        """

        self._description = description

    @property
    def path(self):
        """
        Gets the path of this InlineResponse2006.

        :return: The path of this InlineResponse2006.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this InlineResponse2006.

        :param path: The path of this InlineResponse2006.
        :type: str
        """

        self._path = path

    @property
    def config_string(self):
        """
        Gets the config_string of this InlineResponse2006.

        :return: The config_string of this InlineResponse2006.
        :rtype: str
        """
        return self._config_string

    @config_string.setter
    def config_string(self, config_string):
        """
        Sets the config_string of this InlineResponse2006.

        :param config_string: The config_string of this InlineResponse2006.
        :type: str
        """

        self._config_string = config_string

    @property
    def display_string(self):
        """
        Gets the display_string of this InlineResponse2006.

        :return: The display_string of this InlineResponse2006.
        :rtype: str
        """
        return self._display_string

    @display_string.setter
    def display_string(self, display_string):
        """
        Sets the display_string of this InlineResponse2006.

        :param display_string: The display_string of this InlineResponse2006.
        :type: str
        """

        self._display_string = display_string

    @property
    def editor_type(self):
        """
        Gets the editor_type of this InlineResponse2006.

        :return: The editor_type of this InlineResponse2006.
        :rtype: str
        """
        return self._editor_type

    @editor_type.setter
    def editor_type(self, editor_type):
        """
        Sets the editor_type of this InlineResponse2006.

        :param editor_type: The editor_type of this InlineResponse2006.
        :type: str
        """

        self._editor_type = editor_type

    @property
    def has_children(self):
        """
        Gets the has_children of this InlineResponse2006.

        :return: The has_children of this InlineResponse2006.
        :rtype: bool
        """
        return self._has_children

    @has_children.setter
    def has_children(self, has_children):
        """
        Sets the has_children of this InlineResponse2006.

        :param has_children: The has_children of this InlineResponse2006.
        :type: bool
        """

        self._has_children = has_children

    @property
    def is_configured(self):
        """
        Gets the is_configured of this InlineResponse2006.

        :return: The is_configured of this InlineResponse2006.
        :rtype: bool
        """
        return self._is_configured

    @is_configured.setter
    def is_configured(self, is_configured):
        """
        Sets the is_configured of this InlineResponse2006.

        :param is_configured: The is_configured of this InlineResponse2006.
        :type: bool
        """

        self._is_configured = is_configured

    @property
    def is_initializing(self):
        """
        Gets the is_initializing of this InlineResponse2006.

        :return: The is_initializing of this InlineResponse2006.
        :rtype: bool
        """
        return self._is_initializing

    @is_initializing.setter
    def is_initializing(self, is_initializing):
        """
        Sets the is_initializing of this InlineResponse2006.

        :param is_initializing: The is_initializing of this InlineResponse2006.
        :type: bool
        """

        self._is_initializing = is_initializing

    @property
    def plug_in_name(self):
        """
        Gets the plug_in_name of this InlineResponse2006.

        :return: The plug_in_name of this InlineResponse2006.
        :rtype: str
        """
        return self._plug_in_name

    @plug_in_name.setter
    def plug_in_name(self, plug_in_name):
        """
        Sets the plug_in_name of this InlineResponse2006.

        :param plug_in_name: The plug_in_name of this InlineResponse2006.
        :type: str
        """

        self._plug_in_name = plug_in_name

    @property
    def supported_behaviors(self):
        """
        Gets the supported_behaviors of this InlineResponse2006.

        :return: The supported_behaviors of this InlineResponse2006.
        :rtype: list[str]
        """
        return self._supported_behaviors

    @supported_behaviors.setter
    def supported_behaviors(self, supported_behaviors):
        """
        Sets the supported_behaviors of this InlineResponse2006.

        :param supported_behaviors: The supported_behaviors of this InlineResponse2006.
        :type: list[str]
        """

        self._supported_behaviors = supported_behaviors

    @property
    def variable_mapping(self):
        """
        Gets the variable_mapping of this InlineResponse2006.

        :return: The variable_mapping of this InlineResponse2006.
        :rtype: str
        """
        return self._variable_mapping

    @variable_mapping.setter
    def variable_mapping(self, variable_mapping):
        """
        Sets the variable_mapping of this InlineResponse2006.

        :param variable_mapping: The variable_mapping of this InlineResponse2006.
        :type: str
        """

        self._variable_mapping = variable_mapping

    @property
    def links(self):
        """
        Gets the links of this InlineResponse2006.

        :return: The links of this InlineResponse2006.
        :rtype: InlineResponse2006Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this InlineResponse2006.

        :param links: The links of this InlineResponse2006.
        :type: InlineResponse2006Links
        """

        self._links = links

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2006):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
