# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20021Items(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, web_id=None, id=None, name=None, description=None, path=None, is_connected=None, server_version=None, extended_properties=None, links=None):
        """
        InlineResponse20021Items - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'web_id': 'str',
            'id': 'str',
            'name': 'str',
            'description': 'str',
            'path': 'str',
            'is_connected': 'bool',
            'server_version': 'str',
            'extended_properties': 'dict(str, InlineResponse2009ExtendedProperties)',
            'links': 'InlineResponse20021Links'
        }

        self.attribute_map = {
            'web_id': 'WebId',
            'id': 'Id',
            'name': 'Name',
            'description': 'Description',
            'path': 'Path',
            'is_connected': 'IsConnected',
            'server_version': 'ServerVersion',
            'extended_properties': 'ExtendedProperties',
            'links': 'Links'
        }

        self._web_id = web_id
        self._id = id
        self._name = name
        self._description = description
        self._path = path
        self._is_connected = is_connected
        self._server_version = server_version
        self._extended_properties = extended_properties
        self._links = links

    @property
    def web_id(self):
        """
        Gets the web_id of this InlineResponse20021Items.

        :return: The web_id of this InlineResponse20021Items.
        :rtype: str
        """
        return self._web_id

    @web_id.setter
    def web_id(self, web_id):
        """
        Sets the web_id of this InlineResponse20021Items.

        :param web_id: The web_id of this InlineResponse20021Items.
        :type: str
        """

        self._web_id = web_id

    @property
    def id(self):
        """
        Gets the id of this InlineResponse20021Items.

        :return: The id of this InlineResponse20021Items.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this InlineResponse20021Items.

        :param id: The id of this InlineResponse20021Items.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this InlineResponse20021Items.

        :return: The name of this InlineResponse20021Items.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this InlineResponse20021Items.

        :param name: The name of this InlineResponse20021Items.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this InlineResponse20021Items.

        :return: The description of this InlineResponse20021Items.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this InlineResponse20021Items.

        :param description: The description of this InlineResponse20021Items.
        :type: str
        """

        self._description = description

    @property
    def path(self):
        """
        Gets the path of this InlineResponse20021Items.

        :return: The path of this InlineResponse20021Items.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this InlineResponse20021Items.

        :param path: The path of this InlineResponse20021Items.
        :type: str
        """

        self._path = path

    @property
    def is_connected(self):
        """
        Gets the is_connected of this InlineResponse20021Items.

        :return: The is_connected of this InlineResponse20021Items.
        :rtype: bool
        """
        return self._is_connected

    @is_connected.setter
    def is_connected(self, is_connected):
        """
        Sets the is_connected of this InlineResponse20021Items.

        :param is_connected: The is_connected of this InlineResponse20021Items.
        :type: bool
        """

        self._is_connected = is_connected

    @property
    def server_version(self):
        """
        Gets the server_version of this InlineResponse20021Items.

        :return: The server_version of this InlineResponse20021Items.
        :rtype: str
        """
        return self._server_version

    @server_version.setter
    def server_version(self, server_version):
        """
        Sets the server_version of this InlineResponse20021Items.

        :param server_version: The server_version of this InlineResponse20021Items.
        :type: str
        """

        self._server_version = server_version

    @property
    def extended_properties(self):
        """
        Gets the extended_properties of this InlineResponse20021Items.

        :return: The extended_properties of this InlineResponse20021Items.
        :rtype: dict(str, InlineResponse2009ExtendedProperties)
        """
        return self._extended_properties

    @extended_properties.setter
    def extended_properties(self, extended_properties):
        """
        Sets the extended_properties of this InlineResponse20021Items.

        :param extended_properties: The extended_properties of this InlineResponse20021Items.
        :type: dict(str, InlineResponse2009ExtendedProperties)
        """

        self._extended_properties = extended_properties

    @property
    def links(self):
        """
        Gets the links of this InlineResponse20021Items.

        :return: The links of this InlineResponse20021Items.
        :rtype: InlineResponse20021Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this InlineResponse20021Items.

        :param links: The links of this InlineResponse20021Items.
        :type: InlineResponse20021Links
        """

        self._links = links

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20021Items):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
