# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20051Links(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _self=None, _class=None, reference_unit=None):
        """
        InlineResponse20051Links - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_self': 'str',
            '_class': 'str',
            'reference_unit': 'str'
        }

        self.attribute_map = {
            '_self': 'Self',
            '_class': 'Class',
            'reference_unit': 'ReferenceUnit'
        }

        self.__self = _self
        self.__class = _class
        self._reference_unit = reference_unit

    @property
    def _self(self):
        """
        Gets the _self of this InlineResponse20051Links.

        :return: The _self of this InlineResponse20051Links.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """
        Sets the _self of this InlineResponse20051Links.

        :param _self: The _self of this InlineResponse20051Links.
        :type: str
        """

        self.__self = _self

    @property
    def _class(self):
        """
        Gets the _class of this InlineResponse20051Links.

        :return: The _class of this InlineResponse20051Links.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """
        Sets the _class of this InlineResponse20051Links.

        :param _class: The _class of this InlineResponse20051Links.
        :type: str
        """

        self.__class = _class

    @property
    def reference_unit(self):
        """
        Gets the reference_unit of this InlineResponse20051Links.

        :return: The reference_unit of this InlineResponse20051Links.
        :rtype: str
        """
        return self._reference_unit

    @reference_unit.setter
    def reference_unit(self, reference_unit):
        """
        Sets the reference_unit of this InlineResponse20051Links.

        :param reference_unit: The reference_unit of this InlineResponse20051Links.
        :type: str
        """

        self._reference_unit = reference_unit

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20051Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
