# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20035Links(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _self=None, points=None, enumeration_sets=None):
        """
        InlineResponse20035Links - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_self': 'str',
            'points': 'str',
            'enumeration_sets': 'str'
        }

        self.attribute_map = {
            '_self': 'Self',
            'points': 'Points',
            'enumeration_sets': 'EnumerationSets'
        }

        self.__self = _self
        self._points = points
        self._enumeration_sets = enumeration_sets

    @property
    def _self(self):
        """
        Gets the _self of this InlineResponse20035Links.

        :return: The _self of this InlineResponse20035Links.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """
        Sets the _self of this InlineResponse20035Links.

        :param _self: The _self of this InlineResponse20035Links.
        :type: str
        """

        self.__self = _self

    @property
    def points(self):
        """
        Gets the points of this InlineResponse20035Links.

        :return: The points of this InlineResponse20035Links.
        :rtype: str
        """
        return self._points

    @points.setter
    def points(self, points):
        """
        Sets the points of this InlineResponse20035Links.

        :param points: The points of this InlineResponse20035Links.
        :type: str
        """

        self._points = points

    @property
    def enumeration_sets(self):
        """
        Gets the enumeration_sets of this InlineResponse20035Links.

        :return: The enumeration_sets of this InlineResponse20035Links.
        :rtype: str
        """
        return self._enumeration_sets

    @enumeration_sets.setter
    def enumeration_sets(self, enumeration_sets):
        """
        Sets the enumeration_sets of this InlineResponse20035Links.

        :param enumeration_sets: The enumeration_sets of this InlineResponse20035Links.
        :type: str
        """

        self._enumeration_sets = enumeration_sets

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20035Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
