# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse20030Links(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _self=None, attribute_templates=None, element_template=None, parent=None, categories=None, trait=None):
        """
        InlineResponse20030Links - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_self': 'str',
            'attribute_templates': 'str',
            'element_template': 'str',
            'parent': 'str',
            'categories': 'str',
            'trait': 'str'
        }

        self.attribute_map = {
            '_self': 'Self',
            'attribute_templates': 'AttributeTemplates',
            'element_template': 'ElementTemplate',
            'parent': 'Parent',
            'categories': 'Categories',
            'trait': 'Trait'
        }

        self.__self = _self
        self._attribute_templates = attribute_templates
        self._element_template = element_template
        self._parent = parent
        self._categories = categories
        self._trait = trait

    @property
    def _self(self):
        """
        Gets the _self of this InlineResponse20030Links.

        :return: The _self of this InlineResponse20030Links.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """
        Sets the _self of this InlineResponse20030Links.

        :param _self: The _self of this InlineResponse20030Links.
        :type: str
        """

        self.__self = _self

    @property
    def attribute_templates(self):
        """
        Gets the attribute_templates of this InlineResponse20030Links.

        :return: The attribute_templates of this InlineResponse20030Links.
        :rtype: str
        """
        return self._attribute_templates

    @attribute_templates.setter
    def attribute_templates(self, attribute_templates):
        """
        Sets the attribute_templates of this InlineResponse20030Links.

        :param attribute_templates: The attribute_templates of this InlineResponse20030Links.
        :type: str
        """

        self._attribute_templates = attribute_templates

    @property
    def element_template(self):
        """
        Gets the element_template of this InlineResponse20030Links.

        :return: The element_template of this InlineResponse20030Links.
        :rtype: str
        """
        return self._element_template

    @element_template.setter
    def element_template(self, element_template):
        """
        Sets the element_template of this InlineResponse20030Links.

        :param element_template: The element_template of this InlineResponse20030Links.
        :type: str
        """

        self._element_template = element_template

    @property
    def parent(self):
        """
        Gets the parent of this InlineResponse20030Links.

        :return: The parent of this InlineResponse20030Links.
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """
        Sets the parent of this InlineResponse20030Links.

        :param parent: The parent of this InlineResponse20030Links.
        :type: str
        """

        self._parent = parent

    @property
    def categories(self):
        """
        Gets the categories of this InlineResponse20030Links.

        :return: The categories of this InlineResponse20030Links.
        :rtype: str
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this InlineResponse20030Links.

        :param categories: The categories of this InlineResponse20030Links.
        :type: str
        """

        self._categories = categories

    @property
    def trait(self):
        """
        Gets the trait of this InlineResponse20030Links.

        :return: The trait of this InlineResponse20030Links.
        :rtype: str
        """
        return self._trait

    @trait.setter
    def trait(self, trait):
        """
        Sets the trait of this InlineResponse20030Links.

        :param trait: The trait of this InlineResponse20030Links.
        :type: str
        """

        self._trait = trait

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse20030Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
