# coding: utf-8

"""
    PI Web API 2017 Swagger Spec

    Swagger Spec file that describes PI Web API

    OpenAPI spec version: 1.9.0.266
    Contact: techsupport@osisoft.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PointDTO(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, web_id=None, id=None, name=None, path=None, descriptor=None, point_class=None, point_type=None, digital_set_name=None, engineering_units=None, step=None, future=None, links=None):
        """
        PointDTO - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'web_id': 'str',
            'id': 'int',
            'name': 'str',
            'path': 'str',
            'descriptor': 'str',
            'point_class': 'str',
            'point_type': 'str',
            'digital_set_name': 'str',
            'engineering_units': 'str',
            'step': 'bool',
            'future': 'bool',
            'links': 'InlineResponse20036Links'
        }

        self.attribute_map = {
            'web_id': 'WebId',
            'id': 'Id',
            'name': 'Name',
            'path': 'Path',
            'descriptor': 'Descriptor',
            'point_class': 'PointClass',
            'point_type': 'PointType',
            'digital_set_name': 'DigitalSetName',
            'engineering_units': 'EngineeringUnits',
            'step': 'Step',
            'future': 'Future',
            'links': 'Links'
        }

        self._web_id = web_id
        self._id = id
        self._name = name
        self._path = path
        self._descriptor = descriptor
        self._point_class = point_class
        self._point_type = point_type
        self._digital_set_name = digital_set_name
        self._engineering_units = engineering_units
        self._step = step
        self._future = future
        self._links = links

    @property
    def web_id(self):
        """
        Gets the web_id of this PointDTO.

        :return: The web_id of this PointDTO.
        :rtype: str
        """
        return self._web_id

    @web_id.setter
    def web_id(self, web_id):
        """
        Sets the web_id of this PointDTO.

        :param web_id: The web_id of this PointDTO.
        :type: str
        """

        self._web_id = web_id

    @property
    def id(self):
        """
        Gets the id of this PointDTO.

        :return: The id of this PointDTO.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PointDTO.

        :param id: The id of this PointDTO.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this PointDTO.

        :return: The name of this PointDTO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PointDTO.

        :param name: The name of this PointDTO.
        :type: str
        """

        self._name = name

    @property
    def path(self):
        """
        Gets the path of this PointDTO.

        :return: The path of this PointDTO.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this PointDTO.

        :param path: The path of this PointDTO.
        :type: str
        """

        self._path = path

    @property
    def descriptor(self):
        """
        Gets the descriptor of this PointDTO.

        :return: The descriptor of this PointDTO.
        :rtype: str
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor):
        """
        Sets the descriptor of this PointDTO.

        :param descriptor: The descriptor of this PointDTO.
        :type: str
        """

        self._descriptor = descriptor

    @property
    def point_class(self):
        """
        Gets the point_class of this PointDTO.

        :return: The point_class of this PointDTO.
        :rtype: str
        """
        return self._point_class

    @point_class.setter
    def point_class(self, point_class):
        """
        Sets the point_class of this PointDTO.

        :param point_class: The point_class of this PointDTO.
        :type: str
        """

        self._point_class = point_class

    @property
    def point_type(self):
        """
        Gets the point_type of this PointDTO.

        :return: The point_type of this PointDTO.
        :rtype: str
        """
        return self._point_type

    @point_type.setter
    def point_type(self, point_type):
        """
        Sets the point_type of this PointDTO.

        :param point_type: The point_type of this PointDTO.
        :type: str
        """

        self._point_type = point_type

    @property
    def digital_set_name(self):
        """
        Gets the digital_set_name of this PointDTO.

        :return: The digital_set_name of this PointDTO.
        :rtype: str
        """
        return self._digital_set_name

    @digital_set_name.setter
    def digital_set_name(self, digital_set_name):
        """
        Sets the digital_set_name of this PointDTO.

        :param digital_set_name: The digital_set_name of this PointDTO.
        :type: str
        """

        self._digital_set_name = digital_set_name

    @property
    def engineering_units(self):
        """
        Gets the engineering_units of this PointDTO.

        :return: The engineering_units of this PointDTO.
        :rtype: str
        """
        return self._engineering_units

    @engineering_units.setter
    def engineering_units(self, engineering_units):
        """
        Sets the engineering_units of this PointDTO.

        :param engineering_units: The engineering_units of this PointDTO.
        :type: str
        """

        self._engineering_units = engineering_units

    @property
    def step(self):
        """
        Gets the step of this PointDTO.

        :return: The step of this PointDTO.
        :rtype: bool
        """
        return self._step

    @step.setter
    def step(self, step):
        """
        Sets the step of this PointDTO.

        :param step: The step of this PointDTO.
        :type: bool
        """

        self._step = step

    @property
    def future(self):
        """
        Gets the future of this PointDTO.

        :return: The future of this PointDTO.
        :rtype: bool
        """
        return self._future

    @future.setter
    def future(self, future):
        """
        Sets the future of this PointDTO.

        :param future: The future of this PointDTO.
        :type: bool
        """

        self._future = future

    @property
    def links(self):
        """
        Gets the links of this PointDTO.

        :return: The links of this PointDTO.
        :rtype: InlineResponse20036Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this PointDTO.

        :param links: The links of this PointDTO.
        :type: InlineResponse20036Links
        """

        self._links = links

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PointDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
